[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Form validation for rweb"
edition = "2018"
license = "Apache-2.0"
name = "rweb-form"
repository = "https://github.com/kdy1/rweb.git"
version = "0.1.0"

[dependencies]
